
package principal;

import java.awt.Dimension;
import modelo.factura;

import modelo.imagenfondo;
import modelo.usuarios;
import vista.*;

/**
 *
 * @author darwi
 */
public class mdiSFG22I extends javax.swing.JFrame {
   usuarios u = new usuarios();
   factura fc = new factura();

    /**
     * Creates new form mdiSFG22I
     */
    public mdiSFG22I() {
        initComponents();
        this.setTitle("SISTEMA DE FACTURACION");
        this.setExtendedState(mdiSFG22I.MAXIMIZED_BOTH);
        panel1.setBorder(new imagenfondo());
       
    
       
       
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mParametros = new javax.swing.JMenu();
        pClientes = new javax.swing.JMenuItem();
        pEmpleado = new javax.swing.JMenuItem();
        pProveedores = new javax.swing.JMenuItem();
        pProductos = new javax.swing.JMenuItem();
        mFacturacion = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        pInventario = new javax.swing.JMenuItem();
        mReportes = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        mAyuda = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        mSeguridad = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        CambioClave = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1467, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 51));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(587, 60));

        mParametros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mParametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paramer.png"))); // NOI18N
        mParametros.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        mParametros.setPreferredSize(new java.awt.Dimension(300, 60));

        pClientes.setBackground(new java.awt.Color(0, 0, 0));
        pClientes.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        pClientes.setForeground(new java.awt.Color(255, 255, 255));
        pClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes.png"))); // NOI18N
        pClientes.setText("Clientes");
        pClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        pClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pClientesActionPerformed(evt);
            }
        });
        mParametros.add(pClientes);

        pEmpleado.setBackground(new java.awt.Color(0, 0, 0));
        pEmpleado.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        pEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        pEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleados.png"))); // NOI18N
        pEmpleado.setText("Empleados");
        pEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        pEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pEmpleadoActionPerformed(evt);
            }
        });
        mParametros.add(pEmpleado);

        pProveedores.setBackground(new java.awt.Color(0, 0, 0));
        pProveedores.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        pProveedores.setForeground(new java.awt.Color(255, 255, 255));
        pProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedores.png"))); // NOI18N
        pProveedores.setText("Proveedor");
        pProveedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        pProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pProveedoresActionPerformed(evt);
            }
        });
        mParametros.add(pProveedores);

        pProductos.setBackground(new java.awt.Color(0, 0, 0));
        pProductos.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        pProductos.setForeground(new java.awt.Color(255, 255, 255));
        pProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos.png"))); // NOI18N
        pProductos.setText("Productos");
        pProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        pProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pProductosActionPerformed(evt);
            }
        });
        mParametros.add(pProductos);

        jMenuBar1.add(mParametros);

        mFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FACTU.png"))); // NOI18N
        mFacturacion.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N

        jMenuItem2.setBackground(new java.awt.Color(255, 0, 51));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/facturacion.png"))); // NOI18N
        jMenuItem2.setText("Facturar");
        jMenuItem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mFacturacion.add(jMenuItem2);

        pInventario.setBackground(new java.awt.Color(255, 0, 51));
        pInventario.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        pInventario.setForeground(new java.awt.Color(255, 255, 255));
        pInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inventari.png"))); // NOI18N
        pInventario.setText("Invetario");
        pInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pInventarioActionPerformed(evt);
            }
        });
        mFacturacion.add(pInventario);

        jMenuBar1.add(mFacturacion);

        mReportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/REPORTES.png"))); // NOI18N
        mReportes.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N

        jMenuItem7.setBackground(new java.awt.Color(51, 102, 255));
        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jMenuItem7.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes.png"))); // NOI18N
        jMenuItem7.setText("Clientes");
        jMenuItem7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mReportes.add(jMenuItem7);

        jMenuItem8.setBackground(new java.awt.Color(51, 102, 255));
        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jMenuItem8.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleados.png"))); // NOI18N
        jMenuItem8.setText("Empleados");
        jMenuItem8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mReportes.add(jMenuItem8);

        jMenuItem9.setBackground(new java.awt.Color(51, 102, 255));
        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jMenuItem9.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedores.png"))); // NOI18N
        jMenuItem9.setText("Proveedores");
        jMenuItem9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mReportes.add(jMenuItem9);

        jMenuItem10.setBackground(new java.awt.Color(51, 102, 255));
        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jMenuItem10.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos.png"))); // NOI18N
        jMenuItem10.setText("Productos");
        jMenuItem10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        mReportes.add(jMenuItem10);

        jMenuItem11.setBackground(new java.awt.Color(51, 102, 255));
        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jMenuItem11.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem11.setText("Ventas");
        jMenuItem11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mReportes.add(jMenuItem11);

        jMenuItem12.setBackground(new java.awt.Color(51, 102, 255));
        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jMenuItem12.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inventari.png"))); // NOI18N
        jMenuItem12.setText("Inventarios");
        jMenuItem12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mReportes.add(jMenuItem12);

        jMenuItem13.setBackground(new java.awt.Color(51, 102, 255));
        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jMenuItem13.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem13.setText("Usuarios");
        jMenuItem13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mReportes.add(jMenuItem13);

        jMenuBar1.add(mReportes);

        mAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AYUDA.png"))); // NOI18N
        mAyuda.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N

        jMenuItem14.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jMenuItem14.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem14.setText("Acerca de..");
        jMenuItem14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mAyuda.add(jMenuItem14);

        jMenuItem15.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jMenuItem15.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem15.setText("Manual De Usuario");
        jMenuItem15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        mAyuda.add(jMenuItem15);

        jMenuBar1.add(mAyuda);

        mSeguridad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mSeguridad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SEGU.png"))); // NOI18N
        mSeguridad.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N

        jMenuItem16.setBackground(new java.awt.Color(255, 0, 0));
        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jMenuItem16.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem16.setText("Usuarios");
        jMenuItem16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        mSeguridad.add(jMenuItem16);

        jMenuItem17.setBackground(new java.awt.Color(255, 0, 0));
        jMenuItem17.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jMenuItem17.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem17.setText("Cambiar Clave");
        jMenuItem17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        mSeguridad.add(jMenuItem17);

        jMenuItem18.setBackground(new java.awt.Color(255, 0, 0));
        jMenuItem18.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jMenuItem18.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem18.setText("Reiniciar DB");
        jMenuItem18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        mSeguridad.add(jMenuItem18);

        jMenuBar1.add(mSeguridad);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DATABASE.png"))); // NOI18N

        CambioClave.setText("jMenuItem1");
        CambioClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambioClaveActionPerformed(evt);
            }
        });
        jMenu1.add(CambioClave);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pInventarioActionPerformed
    jifrmInventario m = new jifrmInventario(u);
       panel1.add(m);
       Dimension desktopSize = panel1.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
       m.show();
                    
    }//GEN-LAST:event_pInventarioActionPerformed

    private void pProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pProductosActionPerformed
         jifrmProductos m=new jifrmProductos();
    panel1.add(m);
        Dimension desktopSize = panel1.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
    }//GEN-LAST:event_pProductosActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void pClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pClientesActionPerformed
        jifrmClientes m=new jifrmClientes();
    panel1.add(m);
        Dimension desktopSize = panel1.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
    }//GEN-LAST:event_pClientesActionPerformed

    private void pEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pEmpleadoActionPerformed
            jifrmEmpleados m=new jifrmEmpleados();
        panel1.add(m);
        Dimension desktopSize = panel1.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
    }//GEN-LAST:event_pEmpleadoActionPerformed

    private void pProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pProveedoresActionPerformed
    jifrmProveedores m=new jifrmProveedores();
    panel1.add(m);
        Dimension desktopSize = panel1.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();    
    }//GEN-LAST:event_pProveedoresActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jifrmFactura m=new jifrmFactura();
    panel1.add(m);
        Dimension desktopSize = panel1.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show(); 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void CambioClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambioClaveActionPerformed
        jifrmIngresarcliente m=new jifrmIngresarcliente();
    panel1.add(m);
        Dimension desktopSize = panel1.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show(); 
    }//GEN-LAST:event_CambioClaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdiSFG22I.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdiSFG22I.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdiSFG22I.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdiSFG22I.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdiSFG22I().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CambioClave;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenu mFacturacion;
    private javax.swing.JMenu mParametros;
    private javax.swing.JMenu mReportes;
    private javax.swing.JMenu mSeguridad;
    private javax.swing.JMenuItem pClientes;
    private javax.swing.JMenuItem pEmpleado;
    private javax.swing.JMenuItem pInventario;
    private javax.swing.JMenuItem pProductos;
    private javax.swing.JMenuItem pProveedores;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
//class ImagenFondo extends JPanel{
//        private Image imagen;
//        
//        public void paint(Graphics g){
//            imagen =new ImageIcon(getClass().getResource("imagen12_1.jpg")).getImage();
//            g.drawImage(imagen, 0, 0,getWidth(),getHeight(),this);
//            setOpaque(false);
//            super.paint(g);
//        }
//}

}