/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Component;
import java.sql.Date;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import modelo.inventario;
import modelo.productos;
import modelo.proveedores;
import modelo.usuarios;

/**
 *
 * @author darwi
 */
public class jifrmInventario extends javax.swing.JInternalFrame {
    String titulosInventarioProd[] = {"idProductos", "Descripcion", "Codigo", "Unidad de Medida", "Informacion Nutricional", "Observacion"};
    
    DefaultTableModel dtmProductos = new DefaultTableModel(null, titulosInventarioProd){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    String titulosProveedores[] = {"idProveedores", "Nombre", "Nombre del Contacto", "RUC", "Correo", "Telefono","Direccion","Pagina Web"};
    DefaultTableModel dtmProveedor = new DefaultTableModel(null, titulosProveedores){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    String titulosInventario[] = {"idInventario", "PRODUCTO", "PROVEEDOR", "FECHA DE COMPRA", "FECHA DE ELABORACION", "FECHA DE EXPIRACION","STOK","PRECIO"};
    DefaultTableModel dtmInventario = new DefaultTableModel(null, titulosInventario){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
    String criterio, busqueda,strCodigo;
    
    static ResultSet rs = null;
    
    productos pro = new productos();
    proveedores prov = new proveedores();
    inventario inv = new inventario();
    /**
     * Creates new form jifrmInventario
     */
    public jifrmInventario(usuarios usu) {
         initComponents();
       lblUsuario.setText(usu.getPaUsuario());
        rbtnIdProducto.setSelected(true);
        buscarProducto();
        habilitarBotonesInicio();
        columnasAutoAjustable(tDatosProductos);
        
        rbtnidProveedor.setSelected(true);
        buscarProveedor();
        habilitarBotonesInicio();
        columnasAutoAjustable(tDatosProveedor);
        
        rbtnIdInventario.setSelected(true);
        buscarInventario();
        habilitarBotonesInicio();
        columnasAutoAjustable(tDatosInventario);
    }
        public java.util.Date StringAData(String fecha) {
        Date fechas = null;
        try {
            fechas = (Date) formatoFecha.parse(fecha);
            return fechas;
        } catch (ParseException ex) {
            return null;
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        tbDatos = new javax.swing.JTabbedPane();
        pFormularioDatos = new javax.swing.JPanel();
        lblIdInventario = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        jcFechaCompra = new com.toedter.calendar.JDateChooser();
        jcFechaElaboracion = new com.toedter.calendar.JDateChooser();
        jcFechaExpiracion = new com.toedter.calendar.JDateChooser();
        txtStock = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        rbtnIdInventario = new javax.swing.JRadioButton();
        rbtnIdDescripcionProducto = new javax.swing.JRadioButton();
        Codigo = new javax.swing.JRadioButton();
        txtBusquedainventario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDatosInventario = new javax.swing.JTable();
        lblTotalInventario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        rbtnIdProducto = new javax.swing.JRadioButton();
        rbtnDescripcion = new javax.swing.JRadioButton();
        rbtnCodigo = new javax.swing.JRadioButton();
        txtBusquedaproducto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tDatosProductos = new javax.swing.JTable();
        lblTotalProductos = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        rbtnidProveedor = new javax.swing.JRadioButton();
        rbtnNombreEmpresa = new javax.swing.JRadioButton();
        rbtnRuc = new javax.swing.JRadioButton();
        txtBusquedaproveedores = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tDatosProveedor = new javax.swing.JTable();
        lblTotalProveedores = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("INVENTARIO");

        jToolBar1.setRollover(true);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo2.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setMaximumSize(new java.awt.Dimension(60, 75));
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNuevo);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngegg (1).png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setMaximumSize(new java.awt.Dimension(70, 75));
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setMaximumSize(new java.awt.Dimension(70, 75));
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelar);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar 2.png"))); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setFocusable(false);
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setMaximumSize(new java.awt.Dimension(70, 80));
        btnLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimpiar);

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar3.png"))); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setFocusable(false);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.setMaximumSize(new java.awt.Dimension(80, 75));
        btnActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnActualizar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setMaximumSize(new java.awt.Dimension(70, 75));
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminar);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir_1.png"))); // NOI18N
        jButton7.setText("SALIR");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setMaximumSize(new java.awt.Dimension(60, 75));
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        tbDatos.setBackground(new java.awt.Color(51, 51, 51));
        tbDatos.setForeground(new java.awt.Color(255, 255, 255));
        tbDatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbDatosKeyReleased(evt);
            }
        });

        lblIdInventario.setBorder(javax.swing.BorderFactory.createTitledBorder("idInventario"));

        lblProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        lblProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Proveedor"));

        jcFechaCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de compra"));

        jcFechaElaboracion.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Elaboracion"));

        jcFechaExpiracion.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Expiracion"));

        txtStock.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock"));

        txtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio"));

        lblUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));

        javax.swing.GroupLayout pFormularioDatosLayout = new javax.swing.GroupLayout(pFormularioDatos);
        pFormularioDatos.setLayout(pFormularioDatosLayout);
        pFormularioDatosLayout.setHorizontalGroup(
            pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormularioDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFormularioDatosLayout.createSequentialGroup()
                        .addComponent(lblIdInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))
                    .addGroup(pFormularioDatosLayout.createSequentialGroup()
                        .addComponent(lblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pFormularioDatosLayout.createSequentialGroup()
                        .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcFechaElaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtStock, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcFechaExpiracion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pFormularioDatosLayout.setVerticalGroup(
            pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormularioDatosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jcFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcFechaElaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcFechaExpiracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbDatos.addTab("DATOS INVENTARIO", pFormularioDatos);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por:"));

        buttonGroup1.add(rbtnIdInventario);
        rbtnIdInventario.setText("idInventario");

        buttonGroup1.add(rbtnIdDescripcionProducto);
        rbtnIdDescripcionProducto.setText("Descripcion");

        buttonGroup1.add(Codigo);
        Codigo.setText("Codigo");

        txtBusquedainventario.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese texto de Busqueda:"));
        txtBusquedainventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedainventarioKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBusquedainventario, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rbtnIdInventario)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnIdDescripcionProducto)
                        .addGap(18, 18, 18)
                        .addComponent(Codigo)))
                .addContainerGap(336, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnIdInventario)
                    .addComponent(rbtnIdDescripcionProducto)
                    .addComponent(Codigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBusquedainventario, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        tDatosInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tDatosInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDatosInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tDatosInventario);

        lblTotalInventario.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Registros"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTotalInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotalInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbDatos.addTab("BUSCAR INVENTARIO", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por:"));

        buttonGroup2.add(rbtnIdProducto);
        rbtnIdProducto.setText("idProducto");
        rbtnIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnIdProductoActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtnDescripcion);
        rbtnDescripcion.setText("Descripcion");

        buttonGroup2.add(rbtnCodigo);
        rbtnCodigo.setText("Codigo");

        txtBusquedaproducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese el texto de busqueda"));
        txtBusquedaproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaproductoActionPerformed(evt);
            }
        });
        txtBusquedaproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaproductoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(rbtnIdProducto)
                .addGap(18, 18, 18)
                .addComponent(rbtnDescripcion)
                .addGap(18, 18, 18)
                .addComponent(rbtnCodigo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBusquedaproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnIdProducto)
                    .addComponent(rbtnDescripcion)
                    .addComponent(rbtnCodigo))
                .addGap(18, 18, 18)
                .addComponent(txtBusquedaproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tDatosProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tDatosProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDatosProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tDatosProductos);

        lblTotalProductos.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Registros"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTotalProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(lblTotalProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbDatos.addTab("BUSCAR PRODUCTOS", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 255, 204));

        jPanel7.setBackground(new java.awt.Color(51, 51, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar por:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 16), new java.awt.Color(255, 0, 0))); // NOI18N

        rbtnidProveedor.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup3.add(rbtnidProveedor);
        rbtnidProveedor.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbtnidProveedor.setText("idProveedor");
        rbtnidProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnidProveedorActionPerformed(evt);
            }
        });

        rbtnNombreEmpresa.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup3.add(rbtnNombreEmpresa);
        rbtnNombreEmpresa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbtnNombreEmpresa.setText("NombreEmpresa");

        rbtnRuc.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup3.add(rbtnRuc);
        rbtnRuc.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbtnRuc.setText("RUC");
        rbtnRuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRucActionPerformed(evt);
            }
        });

        txtBusquedaproveedores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese el texto de busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 16), new java.awt.Color(255, 0, 51))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(rbtnidProveedor)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnNombreEmpresa)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnRuc))
                    .addComponent(txtBusquedaproveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 245, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnidProveedor)
                    .addComponent(rbtnNombreEmpresa)
                    .addComponent(rbtnRuc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBusquedaproveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        tDatosProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tDatosProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDatosProveedorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tDatosProveedor);

        lblTotalProveedores.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Registros"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTotalProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(lblTotalProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbDatos.addTab("BUSCAR PROVEEDORES", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbDatos)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(tbDatos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void buscarProducto() {
   String titulos[] = {"IdProducto", "Descripcion", "Codigo", "Unidad Medida", "Informacion Nutricional", "Observacion"};
        dtmProductos.setColumnIdentifiers(titulos);

        productos pro = new productos();
        
        busqueda = txtBusquedaproducto.getText();
        
        if (rbtnIdProducto.isSelected()) {
            criterio = "IDPRODUCTOS";
        }else if (rbtnDescripcion.isSelected()) {
            criterio = "descripcion";
        } else if (rbtnCodigo.isSelected()) {
            criterio = "codigo";
        }
        try {
            rs = pro.SP_S_productosParametro1(criterio, busqueda);
            boolean encuentra = false;
            
            String datos[] = new String[8];
            //Borrar registros de dtm existes
            int f, i;
            f = dtmProductos.getRowCount();
            if (f > 0) {
                for (i = 0; i < f; i++) {
                    dtmProductos.removeRow(0);
                }
            }
            while(rs.next()) {
                datos[0] = (String) rs.getString(1);
                datos[1] = (String) rs.getString(2);
                datos[2] = (String) rs.getString(3);
                datos[3] = (String) rs.getString(4);
                datos[4] = (String) rs.getString(5);
                datos[5] = (String) rs.getString(6);
              

                dtmProductos.addRow(datos);
                encuentra = true;
                

            }
            if (encuentra = false) {
                JOptionPane.showMessageDialog(null, "¡No se encuentra!");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        tDatosProductos.setModel(dtmProductos);
    }
public void buscarProveedor() {
  String titulos1[] = {"IdProveedor", "Nombres", "Nombres Contacto", "Ruc", "Correo", "Telefono","Direccion", "Pagina Web"};
        dtmProveedor.setColumnIdentifiers(titulos1);

        proveedores pr = new proveedores();
        
        busqueda = txtBusquedaproveedores.getText();
        
        if (rbtnidProveedor.isSelected()) {
            criterio = "idproveedores";
        }else if (rbtnNombreEmpresa.isSelected()) {
            criterio = "nombre contacto";
        } else if (rbtnRuc.isSelected()) {
            criterio = "nombre";
        }
        try {
            rs = pr.SP_S_provedoresParametro1(criterio, busqueda);
            boolean encuentra = false;
            
            String datos[] = new String[8];
            //Borrar registros de dtm existes
            int f, i;
            f = dtmProveedor.getRowCount();
            if (f > 0) {
                for (i = 0; i < f; i++) {
                    dtmProveedor.removeRow(0);
                }
            }
            while(rs.next()) {
                datos[0] = (String) rs.getString(1);
                datos[1] = (String) rs.getString(2);
                datos[2] = (String) rs.getString(3);
                datos[3] = (String) rs.getString(4);
                datos[4] = (String) rs.getString(5);
                datos[5] = (String) rs.getString(6);
                datos[6] = (String) rs.getString(7);
                datos[7] = (String) rs.getString(8);

                dtmProveedor.addRow(datos);
                encuentra = true;
              

            }
            if (encuentra = false) {
                JOptionPane.showMessageDialog(null, "¡No se encuentra!");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        tDatosProveedor.setModel(dtmProveedor);
    }
    
    
       
public void buscarInventario() {
     String titulosInventario[] = {"idInventario", "Descripción del Producto", "Codigo", "Unidad de Medida", "Stock", "Precio","Fecha de Compra","Fecha de Elaboracion","Fecha de Expiracion"};
   criterio="";
        busqueda = txtBusquedainventario.getText();
        
        if (rbtnIdInventario.isSelected()) {
            criterio = "idInventario";
        } else if (rbtnIdDescripcionProducto.isSelected()) {
            criterio = "descripcion";
        } else if (Codigo.isSelected()) {
            criterio = "codigo";
        } 
        try {
            rs = inv.listarInventarioProductos(criterio, busqueda);
            boolean encuentra = false;
            String Datos[] = new String[8];
            //Eliminar los datos que se encuentran en la tabla
            int f, i;
            f = dtmInventario.getRowCount();
            if (f > 0) {
                for (i = 0; i < f; i++) {
                    dtmInventario.removeRow(0);
                }
            }
            //Llenar la tabla con la informacion de acuerdo al criterio y el texto de la busqueda
            while (rs.next()) {
                Datos[0] = (String) rs.getString(1);
                Datos[1] = (String) rs.getString(2);
                Datos[2] = (String) rs.getString(3);
                Datos[3] = (String) rs.getString(4);
                Datos[4] = (String) rs.getString(5);
                Datos[5] = (String) rs.getString(6);
                Datos[6] = (String) rs.getString(7);
                Datos[7] = (String) rs.getString(8);
//                Datos[8] = (String) rs.getString(9);

                dtmInventario.addRow(Datos);
                encuentra = true;

            }
            f = dtmInventario.getRowCount();
            lblTotalInventario.setText(String.valueOf(f));
            if (encuentra = false) {
                JOptionPane.showMessageDialog(null, "¡No se encontro registros con los parametros enviados!");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        tDatosInventario.setModel(dtmInventario);
    }
public void cargarDatosProductosFormulario(){
        int fila = tDatosProductos.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Se debe seleccionar un registro");
        }else{
            dtmProductos = (DefaultTableModel) tDatosProductos.getModel();
            pro.setIDPRODUCTO(Integer.parseInt((String)dtmProductos.getValueAt(fila, 0)));
            pro.setPRODESCRIPCION(String.valueOf( dtmProductos.getValueAt(fila, 1)));
            pro.setPROCODIGO((String) dtmProductos.getValueAt(fila, 2));
            pro.setPROUNIDADMEDIDA((String) dtmProductos.getValueAt(fila, 3));


            lblProducto.setText(pro.getIDPRODUCTO()+" "+pro.getPRODESCRIPCION()+" "+pro.getPROCODIGO()+" "+pro.getPROUNIDADMEDIDA());

        }
    }

public void cargarDatosProveedorFormulario(){
          int fila = tDatosProveedor.getSelectedRow();

            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "Se debe seleccionar un registro");
            }else{
                dtmProveedor = (DefaultTableModel) tDatosProveedor.getModel();

                prov.setIDPROVEEDOR(Integer.parseInt((String)tDatosProveedor.getValueAt(fila, 0)));
                prov.setPRONOMBRE((String) tDatosProveedor.getValueAt(fila, 1));
                prov.setPRORUC((String) tDatosProveedor.getValueAt(fila, 3));
                prov.setPROCORREO((String) tDatosProveedor.getValueAt(fila, 4));
                
                lblProveedor.setText(prov.getIDPROVEEDOR()+" "+prov.getPRONOMBRE()+" "+prov.getPRORUC());

            }
    }
public void cargarDatosInventarioFormulario(){
        int fila = tDatosInventario.getSelectedRow();

            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "Se debe seleccionar un registro");
            }else{
                dtmInventario = (DefaultTableModel) tDatosInventario.getModel();
                lblIdInventario.setText((String)tDatosInventario.getValueAt(fila, 0));
                lblProducto.setText((String)tDatosInventario.getValueAt(fila, 1));
                lblProveedor.setText((String)tDatosInventario.getValueAt(fila, 2));
                jcFechaCompra.setDate(Date.valueOf((String)tDatosInventario.getValueAt(fila, 3)));
                jcFechaElaboracion.setDate(Date.valueOf((String)tDatosInventario.getValueAt(fila, 4)));
                jcFechaExpiracion.setDate(Date.valueOf((String)tDatosInventario.getValueAt(fila, 5)));
                txtStock.setText((String)tDatosInventario.getValueAt(fila, 6));
                txtPrecio.setText((String)tDatosInventario.getValueAt(fila, 7));


            }
    }
public void columnasAutoAjustable(JTable tabla) {
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int column = 0; column < tabla.getColumnCount(); column++) {
            TableColumn columnaTabla = tabla.getColumnModel().getColumn(column);
            int anchoMinimo = columnaTabla.getMinWidth();
            int anchoMaximo = columnaTabla.getMaxWidth();

            for (int fila = 0; fila < tabla.getRowCount(); fila++) {
                TableCellRenderer cambiarAnchoCelda = tabla.getCellRenderer(fila, column);
                Component c = tabla.prepareRenderer(cambiarAnchoCelda, fila, column);
                int ancho = c.getPreferredSize().width + tabla.getIntercellSpacing().width;
                anchoMinimo = Math.max(anchoMinimo, ancho);

                //  We've exceeded the maximum width, no need to check other rows
                if (anchoMinimo >= anchoMaximo) {
                    anchoMinimo = anchoMaximo;
                    break;
                }
            }

            columnaTabla.setPreferredWidth(anchoMinimo);
        }
    }
 public void habilitarBotonesProceso() {
        //habilita o desabilita los botones del menu
        btnNuevo.setEnabled(false);
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnLimpiar.setEnabled(true);
        //habilita las cajas de texto del formulario 
        jcFechaCompra.setEnabled(true);
        jcFechaElaboracion.setEnabled(true);
        jcFechaExpiracion.setEnabled(true);
        txtStock.setEnabled(true);
        txtPrecio.setEnabled(true);
    }
 
    public void habilitarBotonesInicio() {
        //habilita o desabilita los botones del menu
        btnNuevo.setEnabled(true);
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnLimpiar.setEnabled(false);
        //bloquea las cajas de texto del formulario 
        jcFechaCompra.setEnabled(false);
        jcFechaElaboracion.setEnabled(false);
        jcFechaExpiracion.setEnabled(false);
        txtStock.setEnabled(false);
        txtPrecio.setEnabled(false);
    }
    public void habilitarBotonesProcesoCargar() {
        //habilita o desabilita los botones del menu
        btnNuevo.setEnabled(false);
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnLimpiar.setEnabled(true);
        //habilita las cajas de texto del formulario 
        jcFechaCompra.setEnabled(true);
        jcFechaElaboracion.setEnabled(true);
        jcFechaExpiracion.setEnabled(true);
        txtStock.setEnabled(true);
        txtPrecio.setEnabled(true);}
    
    

    public void limpiarBuscar() {
        txtBusquedaproducto.setText("");
        buscarProducto();

        txtBusquedaproveedores.setText("");
        buscarProveedor();

        txtBusquedainventario.setText("");
//        buscarInventario();
    }
    
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
 this.lblIdInventario.setText("");
        this.lblProducto.setText("");
        this.lblProveedor.setText("");
        jcFechaCompra.setDate(StringAData(""));
        jcFechaElaboracion.setDate(StringAData(""));
        jcFechaExpiracion.setDate(StringAData(""));
        this.txtStock.setText("");
        this.txtPrecio.setText("");
        habilitarBotonesProceso();
        tbDatos.setSelectedComponent(pFormularioDatos);
        
        
        
 

    
                        
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
String fechaCompra, fechaElaboracion,fechaExpiracion;
        fechaCompra = formatoFecha.format(jcFechaCompra.getDate());
        fechaElaboracion = formatoFecha.format(jcFechaElaboracion.getDate());
        fechaExpiracion = formatoFecha.format(jcFechaExpiracion.getDate());
        
        inv = new inventario(pro.getIDPRODUCTO(),prov.getIDPROVEEDOR(),fechaCompra,fechaElaboracion,fechaExpiracion,Integer.parseInt(txtStock.getText()),Double.parseDouble(txtPrecio.getText()));
        inv.guardar();
        
        this.lblIdInventario.setText("");
        this.lblProducto.setText("");
        this.lblProveedor.setText("");
        jcFechaCompra.setDate(StringAData(""));
        jcFechaElaboracion.setDate(StringAData(""));
        jcFechaExpiracion.setDate(StringAData(""));
        this.txtStock.setText("");
        this.txtPrecio.setText("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
this.lblIdInventario.setText("");
        this.lblProducto.setText("");
        this.lblProveedor.setText("");
        jcFechaCompra.setDate(StringAData(""));
        jcFechaElaboracion.setDate(StringAData(""));
        jcFechaExpiracion.setDate(StringAData(""));
        this.txtStock.setText("");
        this.txtPrecio.setText("");
       
        habilitarBotonesProceso();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
 String fechaCompra, fechaElaboracion,fechaExpiracion;
        fechaCompra = formatoFecha.format(jcFechaCompra.getDate());
        fechaElaboracion = formatoFecha.format(jcFechaElaboracion.getDate());
        fechaExpiracion = formatoFecha.format(jcFechaExpiracion.getDate());
        
        inv = new inventario(Integer.parseInt(lblIdInventario.getText()),Integer.parseInt(lblProducto.getText()),Integer.parseInt(lblProveedor.getText()),fechaCompra,fechaElaboracion,fechaExpiracion,
                Integer.parseInt(txtStock.getText()),Double.parseDouble(txtPrecio.getText()));

        inv.actualizar();
        
        
        buscarInventario();
        this.lblIdInventario.setText("");
        this.lblProducto.setText("");
        this.lblProveedor.setText("");
        jcFechaCompra.setDate(StringAData(""));
        jcFechaElaboracion.setDate(StringAData(""));
        jcFechaExpiracion.setDate(StringAData(""));
        this.txtStock.setText("");
        this.txtPrecio.setText("");
        habilitarBotonesInicio();  
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
  String fechaCompra, fechaElaboracion,fechaExpiracion;
        fechaCompra = formatoFecha.format(jcFechaCompra.getDate());
        fechaElaboracion = formatoFecha.format(jcFechaElaboracion.getDate());
        fechaExpiracion = formatoFecha.format(jcFechaExpiracion.getDate());
        
        inv = new inventario(Integer.parseInt(lblIdInventario.getText()),Integer.parseInt(lblProducto.getText()),Integer.parseInt(lblProveedor.getText()),fechaCompra,fechaElaboracion,fechaExpiracion,
                Integer.parseInt(txtStock.getText()),Double.parseDouble(txtPrecio.getText()));
        inv.eliminar();
        buscarInventario();
        this.lblIdInventario.setText("");
        this.lblProducto.setText("");
        this.lblProveedor.setText("");
        jcFechaCompra.setDate(StringAData(""));
        jcFechaElaboracion.setDate(StringAData(""));
        jcFechaExpiracion.setDate(StringAData(""));
        this.txtStock.setText("");
        this.txtPrecio.setText("");
        habilitarBotonesInicio();     // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void rbtnRucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnRucActionPerformed

    private void rbtnIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnIdProductoActionPerformed

    private void rbtnidProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnidProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnidProveedorActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
 this.lblIdInventario.setText("");
        this.lblProducto.setText("");
        this.lblProveedor.setText("");
        jcFechaCompra.setDate(StringAData(""));
        jcFechaElaboracion.setDate(StringAData(""));
        jcFechaExpiracion.setDate(StringAData(""));
        this.txtStock.setText("");
        this.txtPrecio.setText("");
        habilitarBotonesInicio();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tDatosInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDatosInventarioMouseClicked
  cargarDatosInventarioFormulario();
        if(evt.getClickCount()== 2) {
            tbDatos.setSelectedComponent(pFormularioDatos);
        }
        habilitarBotonesProcesoCargar();        // TODO add your handling code here:
    }//GEN-LAST:event_tDatosInventarioMouseClicked

    private void txtBusquedaproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaproductoActionPerformed

    private void tDatosProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDatosProductosMouseClicked
cargarDatosProductosFormulario();
        if(evt.getClickCount()== 2) {
            tbDatos.setSelectedComponent(pFormularioDatos);
        }
        habilitarBotonesProcesoCargar();           // TODO add your handling code here:
    }//GEN-LAST:event_tDatosProductosMouseClicked

    private void tDatosProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDatosProveedorMouseClicked
cargarDatosProveedorFormulario();
        if(evt.getClickCount()== 2) {
            tbDatos.setSelectedComponent(pFormularioDatos);
        }
        habilitarBotonesProcesoCargar();          // TODO add your handling code here:
    }//GEN-LAST:event_tDatosProveedorMouseClicked

    private void txtBusquedainventarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedainventarioKeyReleased
 buscarInventario();        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedainventarioKeyReleased

    private void txtBusquedaproductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaproductoKeyReleased
buscarProducto();        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaproductoKeyReleased

    private void tbDatosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbDatosKeyReleased
buscarProveedor();        // TODO add your handling code here:
    }//GEN-LAST:event_tbDatosKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Codigo;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private com.toedter.calendar.JDateChooser jcFechaCompra;
    private com.toedter.calendar.JDateChooser jcFechaElaboracion;
    private com.toedter.calendar.JDateChooser jcFechaExpiracion;
    private javax.swing.JLabel lblIdInventario;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblTotalInventario;
    private javax.swing.JLabel lblTotalProductos;
    private javax.swing.JLabel lblTotalProveedores;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pFormularioDatos;
    private javax.swing.JRadioButton rbtnCodigo;
    private javax.swing.JRadioButton rbtnDescripcion;
    private javax.swing.JRadioButton rbtnIdDescripcionProducto;
    private javax.swing.JRadioButton rbtnIdInventario;
    private javax.swing.JRadioButton rbtnIdProducto;
    private javax.swing.JRadioButton rbtnNombreEmpresa;
    private javax.swing.JRadioButton rbtnRuc;
    private javax.swing.JRadioButton rbtnidProveedor;
    private javax.swing.JTable tDatosInventario;
    private javax.swing.JTable tDatosProductos;
    private javax.swing.JTable tDatosProveedor;
    private javax.swing.JTabbedPane tbDatos;
    private javax.swing.JTextField txtBusquedainventario;
    private javax.swing.JTextField txtBusquedaproducto;
    private javax.swing.JTextField txtBusquedaproveedores;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
