/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.awt.Component;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Date;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import modelo.clientes;
import modelo.factura;
import modelo.inventario;
import modelo.productos;
import modelo.proveedores;
import java.lang.String;
import java.text.NumberFormat;
import java.text.ParseException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import modelo.detalleFactura;
import modelo.encabezado;
import modelo.usuarios;
import static vista.jifrmInventario.rs;

/**
 *
 * @author darwi
 */
public class jifrmFactura extends javax.swing.JInternalFrame {
 String titulos[] = {"idProductos", "Descripcion", "Codigo", "Unidad de Medida", "Informacion Nutricional", "Observacion"};
    
    DefaultTableModel dtmP = new DefaultTableModel(null, titulos){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    String titulos2[] = {"IdDetalle","IdEncabezado","IdInventario","detFecha","detSubtotal","detIva","detTotal"};

    DefaultTableModel dtmdetfa = new DefaultTableModel(null, titulos2) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
      };
    String titulos3[] = {"idInventario", "PRODUCTO", "PROVEEDOR", "FECHA DE COMPRA", "FECHA DE ELABORACION", "FECHA DE EXPIRACION","STOK","PRECIO"};

    DefaultTableModel dtmI = new DefaultTableModel(null, titulos3) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
   
    String titulos4[] = {"idCliente", "Apellidos", "Nombres", "Cedula", "Correo", "Telefono", "Direccion"};

    DefaultTableModel dtmC = new DefaultTableModel(null, titulos4) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
       
   
    
   SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
    String criterio, busqueda;
    static ResultSet rs = null;
    Integer busquedaInt;
    factura fac = new factura();
    proveedores pr = new proveedores();
    inventario inv = new inventario();
    clientes cli= new clientes();
    productos pro = new productos();
    detalleFactura detfac= new detalleFactura();
    encabezado enc = new encabezado();
    usuarios usua = new usuarios();
    DefaultTableModel modelo;
    
    
     Double Subtotal;
     Double iva ;
     Double Total;
     Double totalp ;
     int stock;
   
    /**
     * Creates new form jifrmFactura
     */
    public jifrmFactura() {
        initComponents();
        
        Calendar c2 = new GregorianCalendar();
        jcFecha.setCalendar(c2);
              
//        lblUsuario.setText();
        modelo = new DefaultTableModel();
        modelo.addColumn("codigo del producto");
        modelo.addColumn("Nombre del producto");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Total");
        
        this.tDatosfa.setModel(modelo);
        
        
    
        rbtnIdCliente.setSelected(true);
        buscarCliente();
        habilitarBotonesInicio();
        columnasAutoAjustable(tDatoscliente);
        
        
        
        rbtnIdinventario.setSelected(true);
        buscarInventario();
        habilitarBotonesInicio();
        columnasAutoAjustable(tDatosinventario);
        
        lblUsuario.setText("1");
        
        
//        rbtidDetalle.setSelected(true);
//        buscarDetalle();
        habilitarBotonesInicio();
        columnasAutoAjustable(tDatoscliente);
        
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        tbDatos = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        pBuscarcliente = new javax.swing.JPanel();
        rbtnIdCliente = new javax.swing.JRadioButton();
        rbtnApellido = new javax.swing.JRadioButton();
        rbtnNombre = new javax.swing.JRadioButton();
        rbtnCedula = new javax.swing.JRadioButton();
        txtBusqueda = new javax.swing.JTextField();
        lblTotalRegistros = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tDatoscliente = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        pBuscar2 = new javax.swing.JPanel();
        rbtnIdinventario = new javax.swing.JRadioButton();
        rbtnProducto = new javax.swing.JRadioButton();
        rbtnProveedor = new javax.swing.JRadioButton();
        txtBusquedainventario = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tDatosinventario = new javax.swing.JTable();
        lblTotalInventario = new javax.swing.JLabel();
        pformularioFactura = new javax.swing.JPanel();
        txtIdcliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDatosfa = new javax.swing.JTable();
        btnvender = new javax.swing.JButton();
        txtRuc = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtIva = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jcFecha = new com.toedter.calendar.JDateChooser();
        btnAgregar = new javax.swing.JButton();
        txtCodigoproducto = new javax.swing.JTextField();
        txtNombreproducto = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnQuitar = new javax.swing.JButton();
        txtStock = new javax.swing.JTextField();
        txtNumfactura = new javax.swing.JTextField();
        lblIdinventario = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tDatos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        totalRegistros = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jToolBar1.setRollover(true);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo2.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setMaximumSize(new java.awt.Dimension(60, 75));
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNuevo);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setMaximumSize(new java.awt.Dimension(70, 75));
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelar);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar 2.png"))); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setFocusable(false);
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setMaximumSize(new java.awt.Dimension(70, 80));
        btnLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimpiar);

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar3.png"))); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setFocusable(false);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.setMaximumSize(new java.awt.Dimension(80, 75));
        btnActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnActualizar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setMaximumSize(new java.awt.Dimension(70, 75));
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminar);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir_1.png"))); // NOI18N
        jButton7.setText("SALIR");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setMaximumSize(new java.awt.Dimension(60, 75));
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        tbDatos.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N

        pBuscarcliente.setBackground(new java.awt.Color(204, 204, 204));
        pBuscarcliente.setBorder(javax.swing.BorderFactory.createTitledBorder("BUSCR POR:"));

        buttonGroup1.add(rbtnIdCliente);
        rbtnIdCliente.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rbtnIdCliente.setText("ID CLIENTE");
        rbtnIdCliente.setToolTipText("");
        rbtnIdCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnIdClienteMouseClicked(evt);
            }
        });
        rbtnIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnIdClienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnApellido);
        rbtnApellido.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rbtnApellido.setText("APELLIDO");
        rbtnApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnApellidoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnNombre);
        rbtnNombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rbtnNombre.setText("NOMBRE");

        buttonGroup1.add(rbtnCedula);
        rbtnCedula.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rbtnCedula.setText("CEDULA");

        txtBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESE EL TEXTO DE BUSQUEDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        lblTotalRegistros.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTotalRegistros.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Registros"));

        tDatoscliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tDatoscliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDatosclienteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tDatoscliente);

        javax.swing.GroupLayout pBuscarclienteLayout = new javax.swing.GroupLayout(pBuscarcliente);
        pBuscarcliente.setLayout(pBuscarclienteLayout);
        pBuscarclienteLayout.setHorizontalGroup(
            pBuscarclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBuscarclienteLayout.createSequentialGroup()
                .addGroup(pBuscarclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pBuscarclienteLayout.createSequentialGroup()
                        .addGroup(pBuscarclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pBuscarclienteLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(rbtnIdCliente)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnApellido)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnNombre)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnCedula))
                            .addGroup(pBuscarclienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pBuscarclienteLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 338, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        pBuscarclienteLayout.setVerticalGroup(
            pBuscarclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBuscarclienteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pBuscarclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnIdCliente)
                    .addComponent(rbtnApellido)
                    .addComponent(rbtnNombre)
                    .addComponent(rbtnCedula))
                .addGap(39, 39, 39)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lblTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pBuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 161, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pBuscarcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbDatos.addTab(" CLIENTE ", jPanel2);

        pBuscar2.setBackground(new java.awt.Color(255, 255, 255));
        pBuscar2.setBorder(javax.swing.BorderFactory.createTitledBorder("BUSCR POR:"));

        buttonGroup2.add(rbtnIdinventario);
        rbtnIdinventario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rbtnIdinventario.setText("ID INVENTARIO");

        buttonGroup2.add(rbtnProducto);
        rbtnProducto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rbtnProducto.setText("PRODUCTO");

        buttonGroup2.add(rbtnProveedor);
        rbtnProveedor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rbtnProveedor.setText("PROVEEDOR");

        txtBusquedainventario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESE EL TEXTO DE BUSQUEDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(255, 0, 0))); // NOI18N
        txtBusquedainventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedainventarioKeyReleased(evt);
            }
        });

        tDatosinventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tDatosinventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDatosinventarioMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tDatosinventario);

        lblTotalInventario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalInventario.setBorder(javax.swing.BorderFactory.createTitledBorder("TOTAL REGISTRO"));

        javax.swing.GroupLayout pBuscar2Layout = new javax.swing.GroupLayout(pBuscar2);
        pBuscar2.setLayout(pBuscar2Layout);
        pBuscar2Layout.setHorizontalGroup(
            pBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBuscar2Layout.createSequentialGroup()
                .addGroup(pBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pBuscar2Layout.createSequentialGroup()
                        .addGroup(pBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pBuscar2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtBusquedainventario, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pBuscar2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(rbtnIdinventario)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnProducto)
                                .addGap(38, 38, 38)
                                .addComponent(rbtnProveedor))
                            .addGroup(pBuscar2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblTotalInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 498, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pBuscar2Layout.setVerticalGroup(
            pBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBuscar2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnIdinventario)
                    .addComponent(rbtnProducto)
                    .addComponent(rbtnProveedor))
                .addGap(39, 39, 39)
                .addComponent(txtBusquedainventario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(pBuscar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pBuscar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbDatos.addTab(" INVENTARIO", jPanel3);

        pformularioFactura.setBackground(new java.awt.Color(204, 204, 255));

        txtIdcliente.setEditable(false);
        txtIdcliente.setBackground(new java.awt.Color(0, 0, 0));
        txtIdcliente.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtIdcliente.setForeground(new java.awt.Color(255, 255, 255));
        txtIdcliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Numero de cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        tDatosfa.setBackground(new java.awt.Color(255, 0, 0));
        tDatosfa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "fecha de compra", "id del producto", "Precio", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tDatosfa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tDatosfaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tDatosfa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tDatosfaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tDatosfa);

        btnvender.setText("VENDER $");
        btnvender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvenderActionPerformed(evt);
            }
        });

        txtRuc.setEditable(false);
        txtRuc.setBackground(new java.awt.Color(0, 0, 0));
        txtRuc.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtRuc.setForeground(new java.awt.Color(255, 255, 255));
        txtRuc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RUC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setBackground(new java.awt.Color(0, 0, 0));
        txtNombreCliente.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtNombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombres completos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        txtIva.setEditable(false);
        txtIva.setBorder(javax.swing.BorderFactory.createTitledBorder("IVA"));

        txtSubtotal.setEditable(false);
        txtSubtotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Subtotal"));
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });

        txtCorreo.setEditable(false);
        txtCorreo.setBackground(new java.awt.Color(0, 0, 0));
        txtCorreo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COREO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        lblUsuario.setBackground(new java.awt.Color(255, 51, 0));
        lblUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID ENCABEZADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        txtTotal.setEditable(false);
        txtTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));

        txtDireccion.setEditable(false);
        txtDireccion.setBackground(new java.awt.Color(0, 0, 0));
        txtDireccion.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LUGAR DONDE VIVE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        jcFecha.setBackground(new java.awt.Color(0, 0, 0));
        jcFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        btnAgregar.setText("AGREGAR");
        btnAgregar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtCodigoproducto.setEditable(false);
        txtCodigoproducto.setBackground(new java.awt.Color(204, 0, 204));
        txtCodigoproducto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCodigoproducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo Producto"));

        txtNombreproducto.setEditable(false);
        txtNombreproducto.setBackground(new java.awt.Color(204, 0, 204));
        txtNombreproducto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNombreproducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre Producto"));

        txtPrecio.setEditable(false);
        txtPrecio.setBackground(new java.awt.Color(255, 0, 255));
        txtPrecio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio"));

        txtCantidad.setBackground(new java.awt.Color(153, 255, 255));
        txtCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad"));

        btnQuitar.setText("QUITAR");
        btnQuitar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        txtStock.setEditable(false);
        txtStock.setBackground(new java.awt.Color(255, 0, 255));
        txtStock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtStock.setBorder(javax.swing.BorderFactory.createTitledBorder("Stok"));
        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });

        txtNumfactura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NUM FACTURA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 0, 0))); // NOI18N

        lblIdinventario.setBackground(new java.awt.Color(51, 51, 255));
        lblIdinventario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID INVENTARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        btnGenerar.setText("GENERARA");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        tDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tDatos);

        totalRegistros.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Registros"));

        javax.swing.GroupLayout pformularioFacturaLayout = new javax.swing.GroupLayout(pformularioFactura);
        pformularioFactura.setLayout(pformularioFacturaLayout);
        pformularioFacturaLayout.setHorizontalGroup(
            pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pformularioFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pformularioFacturaLayout.createSequentialGroup()
                        .addGap(895, 895, 895)
                        .addComponent(btnGenerar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pformularioFacturaLayout.createSequentialGroup()
                        .addGroup(pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDireccion)
                                .addComponent(txtRuc)
                                .addComponent(txtCorreo)
                                .addComponent(txtIdcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pformularioFacturaLayout.createSequentialGroup()
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtStock)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pformularioFacturaLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(btnvender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(45, 45, 45)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE))
                            .addGroup(pformularioFacturaLayout.createSequentialGroup()
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pformularioFacturaLayout.createSequentialGroup()
                        .addGroup(pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecio)
                            .addGroup(pformularioFacturaLayout.createSequentialGroup()
                                .addComponent(txtCodigoproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 37, Short.MAX_VALUE)))
                        .addGroup(pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pformularioFacturaLayout.createSequentialGroup()
                                .addGap(364, 364, 364)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pformularioFacturaLayout.createSequentialGroup()
                                .addGap(522, 522, 522)
                                .addComponent(totalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pformularioFacturaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pformularioFacturaLayout.createSequentialGroup()
                                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblIdinventario, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pformularioFacturaLayout.setVerticalGroup(
            pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pformularioFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdinventario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pformularioFacturaLayout.createSequentialGroup()
                        .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnvender, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pformularioFacturaLayout.createSequentialGroup()
                        .addGroup(pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pformularioFacturaLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtIdcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pformularioFacturaLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pformularioFacturaLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(totalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pformularioFacturaLayout.createSequentialGroup()
                                .addGroup(pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pformularioFacturaLayout.createSequentialGroup()
                                        .addComponent(txtCodigoproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pformularioFacturaLayout.createSequentialGroup()
                                        .addComponent(txtNombreproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pformularioFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(28, 28, 28)
                .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        tbDatos.addTab("FACTURA", pformularioFactura);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbDatos)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbDatos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void buscarCliente() {
        String titulos4[] = {"IdCliente", "Apellidos", "Nombres", "Cedula", "Correo", "Telefono","Direccion"};
        dtmC.setColumnIdentifiers(titulos4);

        clientes cli = new clientes();
        
        busqueda = txtBusqueda.getText();
        
        if (rbtnIdCliente.isSelected()) {
            criterio = "IDCLIENTE";
        }else if (rbtnApellido.isSelected()) {
            criterio = "apellidos";
        } else if (rbtnNombre.isSelected()) {
            criterio = "nombres";
        } else if (rbtnCedula.isSelected()) {
            criterio = "cedula";
        }
        try {
            rs = cli.listarClientesPorParametro1(criterio, busqueda);
            boolean encuentra = false;
            
            String datos[] = new String[7];
            //Borrar registros de dtm existes
            int f, i;
            f = dtmC.getRowCount();
            if (f > 0) {
                for (i = 0; i < f; i++) {
                    dtmC.removeRow(0);
                }
            }
            while(rs.next()) {
                datos[0] = (String) rs.getString(1);
                datos[1] = (String) rs.getString(2);
                datos[2] = (String) rs.getString(3);
                datos[3] = (String) rs.getString(4);
                datos[4] = (String) rs.getString(5);
                datos[5] = (String) rs.getString(6);
                datos[6] = (String) rs.getString(7);

                dtmC.addRow(datos);
                encuentra = true;
            
            f = dtmC.getRowCount();
            lblTotalRegistros.setText(String.valueOf(f));
            }
            if (encuentra = false) {
                JOptionPane.showMessageDialog(null, "¡No se encuentra!");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        tDatoscliente.setModel(dtmC);
    }
      public void buscarInventario() {
         criterio="";
        busqueda = txtBusquedainventario.getText();
        
        if (rbtnIdinventario.isSelected()) {
            criterio = "idInventario";
        } else if (rbtnProducto.isSelected()) {
            criterio = "descripcion";
        } else if (rbtnProveedor.isSelected()) {
            criterio = "codigo";
        } 
        try {
            rs = inv.listarInventarioPorParametro(criterio, busqueda);
            boolean encuentra = false;
            String Datos[] = new String[8];
            //Eliminar los datos que se encuentran en la tabla
            int f, i;
            f = dtmI.getRowCount();
            if (f > 0) {
                for (i = 0; i < f; i++) {
                    dtmI.removeRow(0);
                }
            }
            //Llenar la tabla con la informacion de acuerdo al criterio y el texto de la busqueda
            while (rs.next()) {
                Datos[0] = (String) rs.getString(1);
                Datos[1] = (String) rs.getString(2);
                Datos[2] = (String) rs.getString(3);
                Datos[3] = (String) rs.getString(4);
                Datos[4] = (String) rs.getString(5);
                Datos[5] = (String) rs.getString(6);
                Datos[6] = (String) rs.getString(7);
                Datos[7] = (String) rs.getString(8);
//                Datos[8] = (String) rs.getString(9);

                dtmI.addRow(Datos);
                encuentra = true;

            }
            f = dtmI.getRowCount();
            lblTotalInventario.setText(String.valueOf(f));
            if (encuentra = false) {
                JOptionPane.showMessageDialog(null, "¡No se encontro registros con los parametros enviados!");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        tDatosinventario.setModel(dtmI);
    }
//     public void buscarDetalle() {
//       
//       
//        busqueda = txtBusqueda.getText();
//        
//        if (rbtnIdinventario.isSelected()) {
//            criterio = "idInventario";
//        } else if (rbtnProducto.isSelected()) {
//            criterio = "descripcion";
//        } else if (rbtnProveedor.isSelected()) {
//            criterio = "codigo";
//        } 
//        try {
//            dtmdetfa = detfac.listarDetallePorParametro(criterio, busqueda);
//            boolean encuentra = false;
//            String Datos[] = new String[7];
//            //Eliminar los datos que se encuentran en la tabla
//            int f, i;
//            f = dtmdetfa.getRowCount();
//            if (f > 0) {
//                for (i = 0; i < f; i++) {
//                    dtmdetfa.removeRow(0);
//                }
//            }
//            //Llenar la tabla con la informacion de acuerdo al criterio y el texto de la busqueda
//            while (rs.next()) {
//                Datos[0] = (String) rs.getString(1);
//                Datos[1] = (String) rs.getString(2);
//                Datos[2] = (String) rs.getString(3);
//                Datos[3] = (String) rs.getString(4);
//                Datos[4] = (String) rs.getString(5);
//                Datos[5] = (String) rs.getString(6);
//                Datos[6] = (String) rs.getString(7);
////                Datos[7] = (String) rs.getString(8);
////                Datos[8] = (String) rs.getString(9);
//
//                dtmdetfa.addRow(Datos);
//                encuentra = true;
//
//            }
//            f = dtmdetfa.getRowCount();
//            lblTotalInventario.setText(String.valueOf(f));
//            if (encuentra = false) {
//                JOptionPane.showMessageDialog(null, "¡No se encontro registros con los parametros enviados!");
//            }
//
//        } catch (Exception ex) {
//            ex.printStackTrace();
//        }
//        tbdatosDetalle.setModel(dtmdetfa);
//    }
    
     public void habilitarBotonesInicio(){
        //habilita o desabilita los botones del menu
         btnNuevo.setEnabled(true);
        
        btnCancelar.setEnabled(false);
//        btnGuardar.setEnabled(false);
        btnLimpiar.setEnabled(false);
        //bloquea las cajas de texto del formulario 
        jcFecha.setEnabled(true);
        txtNombreCliente.setEnabled(true);
        txtRuc.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtCorreo.setEnabled(true);
    }
    public void columnasAutoAjustable(JTable tabla) {
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int column = 0; column < tabla.getColumnCount(); column++) {
            TableColumn columnaTabla = tabla.getColumnModel().getColumn(column);
            int anchoMinimo = columnaTabla.getMinWidth();
            int anchoMaximo = columnaTabla.getMaxWidth();

            for (int fila = 0; fila < tabla.getRowCount(); fila++) {
                TableCellRenderer cambiarAnchoCelda = tabla.getCellRenderer(fila, column);
                Component c = tabla.prepareRenderer(cambiarAnchoCelda, fila, column);
                int ancho = c.getPreferredSize().width + tabla.getIntercellSpacing().width;
                anchoMinimo = Math.max(anchoMinimo, ancho);

                //  We've exceeded the maximum width, no need to check other rows
                if (anchoMinimo >= anchoMaximo) {
                    anchoMinimo = anchoMaximo;
                    break;
                }
            }

            columnaTabla.setPreferredWidth(anchoMinimo);
        }
    }
     public java.util.Date StringAData (String fecha){
        Date fechas = null;
        try{
            fechas=  (Date) formatoFecha.parse(fecha);
            return fechas;
        }catch (ParseException ex){
             return null;
        }
    }
      public void habilitarBotonesProceso(){
        //habilita o desabilita los botones del menu
        btnNuevo.setEnabled(false);
        btnCancelar.setEnabled(true);
//        btnGuardar.setEnabled(true);
        btnLimpiar.setEnabled(true);
        //habilita las cajas de texto del formulario 
        jcFecha.setEnabled(true);
        txtNombreCliente.setEnabled(true);
        txtRuc.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtCorreo.setEnabled(true);
    }
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.txtIdcliente.setText("");
      jcFecha.setDate(StringAData(""));
      this.txtNombreCliente.setText("");
      this.txtRuc.setText("");
      this.txtDireccion.setText("");
      this.txtCorreo.setText("");
      this.txtPrecio.setText("");
      this.txtCodigoproducto.setText("");
      this.txtNombreproducto.setText("");
      this.txtPrecio.setText("");
      this.txtStock.setText("");
      this.txtSubtotal.setText("");
      this.txtIva.setText("");
      this.txtPrecio.setText("");
      this.txtNumfactura.setText("");
      this.txtTotal.setText("");
        habilitarBotonesProceso();
        Calendar c2 = new GregorianCalendar();
        jcFecha.setCalendar(c2);
        tbDatos.setSelectedComponent(pformularioFactura);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.txtIdcliente.setText("");
      jcFecha.setDate(StringAData(""));
      this.txtNombreCliente.setText("");
      this.txtRuc.setText("");
      this.txtDireccion.setText("");
      this.txtCorreo.setText("");
      this.txtPrecio.setText("");
      this.txtCodigoproducto.setText("");
      this.txtNombreproducto.setText("");
      this.txtPrecio.setText("");
      this.txtStock.setText("");
      this.txtSubtotal.setText("");
      this.txtIva.setText("");
      this.txtPrecio.setText("");
      this.txtNumfactura.setText("");
      this.txtTotal.setText("");
      
      modelo.getDataVector().removeAllElements();
      tDatosfa.updateUI();
        
      habilitarBotonesInicio();
             // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
//        String fechaCompra, fechaElaboracion,fechaExpiracion;
//        fechaCompra = formatoFecha.format(jcFechaCompra.getDate());
//        fechaElaboracion = formatoFecha.format(jcFechaElaboracion.getDate());
//        fechaExpiracion = formatoFecha.format(jcFechaExpiracion.getDate());
//
//        inv = new inventario(Integer.parseInt(lblIdInventario.getText()),Integer.parseInt(lblProducto.getText()),Integer.parseInt(lblProveedor.getText()),fechaCompra,fechaElaboracion,fechaExpiracion,
//            Integer.parseInt(txtStock.getText()),Double.parseDouble(txtPrecio.getText()));
//
//        inv.actualizar();
//
//        buscarInventario();
//        this.lblIdInventario.setText("");
//        this.lblProducto.setText("");
//        this.lblProveedor.setText("");
//        jcFechaCompra.setDate(StringAData(""));
//        jcFechaElaboracion.setDate(StringAData(""));
//        jcFechaExpiracion.setDate(StringAData(""));
//        this.txtStock.setText("");
//        this.txtPrecio.setText("");
//        habilitarBotonesInicio();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
//        String fechaCompra, fechaElaboracion,fechaExpiracion;
//        fechaCompra = formatoFecha.format(jcFechaCompra.getDate());
//        fechaElaboracion = formatoFecha.format(jcFechaElaboracion.getDate());
//        fechaExpiracion = formatoFecha.format(jcFechaExpiracion.getDate());
//
//        inv = new inventario(Integer.parseInt(lblIdInventario.getText()),Integer.parseInt(lblProducto.getText()),Integer.parseInt(lblProveedor.getText()),fechaCompra,fechaElaboracion,fechaExpiracion,
//            Integer.parseInt(txtStock.getText()),Double.parseDouble(txtPrecio.getText()));
//        inv.eliminar();
//        buscarInventario();
//        this.lblIdInventario.setText("");
//        this.lblProducto.setText("");
//        this.lblProveedor.setText("");
//        jcFechaCompra.setDate(StringAData(""));
//        jcFechaElaboracion.setDate(StringAData(""));
//        jcFechaExpiracion.setDate(StringAData(""));
//        this.txtStock.setText("");
//        this.txtPrecio.setText("");
//        habilitarBotonesInicio();     // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // if(evt.getSource()==btnGenerar){
            //
            //       if(lblIdinventario.getText().length()==0||lblUsuario.getText().length()==0||txtTotal.getText().length()==0
                ////               email.getText().length()==0||contrasena.getText().length()==0||contrasenia.getText().length()==0||
                ////               (hombre.isSelected()==false && mujer.isSelected()==false)
                //               ){
                //           JOptionPane.showMessageDialog(null, "debe ingresar sus datos ");
                //       }else{
                //           try{ BufferedWriter bw=new BufferedWriter(new FileWriter("D://prueba.txt",true));
                    //               String nombres = lblIdinventario.getText();
                    //               String apellidos = lblUsuario.getText();
                    //
                    //
                    //
                    //
                    //
                    //
                    //
                    //           } catch (IOException e) {
                    //              e.printStackTrace();
                    //
                    //           }
                //
                //       }
            //       }        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed

        eliminarvalor();
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        agrgarProducto();
        operaciones();

        cargarClientesFormulario();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void btnvenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvenderActionPerformed

        String Fecha;
        Fecha= formatoFecha.format(jcFecha.getDate());

        detfac = new detalleFactura(Integer.parseInt(txtNumfactura.getText()),
            Integer.parseInt(lblIdinventario.getText()),Fecha,
            Double.parseDouble(txtSubtotal.getText()),Double.parseDouble(txtIva.getText()),Double.parseDouble(txtTotal.getText())
        );

        Fecha= formatoFecha.format(jcFecha.getDate());

        enc = new encabezado(Integer.parseInt(txtIdcliente.getText()),
            Integer.parseInt(lblUsuario.getText()),
            Integer.parseInt(txtNumfactura.getText()),
            Fecha);
        //        inv.consultarStock();
        //        inv.actualizarStock(txtCantidad);
        enc.guardarenc();
        detfac.guardar();

        //        enc = new encabezado(cli.getIdCliente(),usua.getIdUsuario(),txtNumfactura.getText(),String.valueOf(LocalDateTime.now()));
        //        if(enc.guardarenc()==true){
            //            System.out.println("Graba Encabezado");
            //            for(int i=0;i<tDatosFactura.getRowCount();i++){
                //                Subtotal = Subtotal + Double.parseDouble(tDatosFactura.getValueAt(i, 3).toString());
                //                detfac = new detallefactura(enc.consultarMaxId(),Integer.parseInt(tDatosFactura.getValueAt(i, 0).toString()),String.valueOf(LocalDateTime.now()),Subtotal,Subtotal*0.12,((Subtotal*0.12)+Subtotal));
                //                detfac.mostrarDatos();
                //                if(detfac.guardar()){
                    //                    inv.actualizarStock(Integer.parseInt(tDatosFactura.getValueAt(i, 0).toString()),Integer.parseInt(tDatosFactura.getValueAt(i, 2).toString()));
                    //                    System.out.println("");
                    //                }
                //            }
            //
            //        }
    }//GEN-LAST:event_btnvenderActionPerformed

    private void tDatosfaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tDatosfaKeyReleased

    }//GEN-LAST:event_tDatosfaKeyReleased

    private void tDatosfaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tDatosfaAncestorAdded

    }//GEN-LAST:event_tDatosfaAncestorAdded

    private void tDatosinventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDatosinventarioMouseClicked
        cargarDatosProductoInventarioFormulario();
        if(evt.getClickCount()== 2) {
            tbDatos.setSelectedComponent(pformularioFactura);

        }
        habilitarBotonesProcesoCargar();
    }//GEN-LAST:event_tDatosinventarioMouseClicked

    private void txtBusquedainventarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedainventarioKeyReleased
        buscarInventario();
    }//GEN-LAST:event_txtBusquedainventarioKeyReleased

    private void tDatosclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDatosclienteMouseClicked
        cargarClientesFormulario();
        if(evt.getClickCount()== 2) {
            tbDatos.setSelectedComponent(pformularioFactura);
        }
        habilitarBotonesProcesoCargar();
    }//GEN-LAST:event_tDatosclienteMouseClicked

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        buscarCliente();
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void rbtnApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnApellidoActionPerformed

    private void rbtnIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnIdClienteActionPerformed

    }//GEN-LAST:event_rbtnIdClienteActionPerformed

    private void rbtnIdClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnIdClienteMouseClicked

    }//GEN-LAST:event_rbtnIdClienteMouseClicked

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed
 public void agrgarProducto(){
        String []info = new String[5];
       
        info[0]=txtCodigoproducto.getText();
        info[1]=txtNombreproducto.getText();
        info[2]=txtPrecio.getText();
        info[3]=txtCantidad.getText();
        Double totalp = Double.parseDouble(txtPrecio.getText()) *Double.parseDouble(txtCantidad.getText());
        info[4]=totalp.toString();
        
        modelo.addRow(info);
        tDatosfa.setModel(modelo);
        
//        lblIdinventario.setText("");
        txtCodigoproducto.setText("");
        txtNombreproducto.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");
    }
   private int count=0;
    private void operaciones(){
        double S=0,iva,total;
        for(int i=0;i<modelo.getRowCount();i++){
                S=S+Double.parseDouble(modelo.getValueAt(i, 4).toString());
            }
            S=redondear(S);
            txtSubtotal.setText(String.valueOf(S));
            iva=0.12*S;
            iva=redondear(iva);
            total=S+iva;
            total=redondear(total);
            txtIva.setText(String.valueOf(iva));
            txtTotal.setText(String.valueOf(total));
            
            
    }
    private double redondear(double num){
        return Math.rint(num*100)/100;} public void eliminarvalor(){

        int fila;
          
        if(modelo.getRowCount()>0){
            if (tDatosfa.getSelectedRow()!=-1){
                fila=tDatosfa.getSelectedRow();
                modelo.removeRow(fila);
                operaciones();
                
            }else{
                JOptionPane.showMessageDialog(null, "Selecione una fila");
            }
        }
               else{
                    JOptionPane.showMessageDialog(null, "No hay filas en la tabla");
                }
 
    }
 public void cargarClientesFormulario() {

           int fila = tDatoscliente.getSelectedRow();
            if (fila == -2) {
                JOptionPane.showMessageDialog(null, "Se debe seleccionar un registro");
            } else {
                dtmC = (DefaultTableModel) tDatoscliente.getModel();
                cli = new clientes(Integer.parseInt(dtmC.getValueAt(fila, 0).toString()),
                        (String) dtmC.getValueAt(fila, 1),
                        (String) dtmC.getValueAt(fila, 2),
                        (String) dtmC.getValueAt(fila, 3),
                        (String) dtmC.getValueAt(fila, 4),
                        (String) dtmC.getValueAt(fila, 5),
                        (String) dtmC.getValueAt(fila, 6));
            }

         System.out.println(cli.mostrarDatos());
        txtIdcliente.setText(cli.getIdCliente().toString());
        txtNombreCliente.setText(cli.getApellidos()+" "+cli.getNombres());
        txtRuc.setText(cli.getCedula());
        txtCorreo.setText(cli.getCorreo());
        txtDireccion.setText(cli.getDireccion());
        
        }
       public void habilitarBotonesProcesoCargar(){
        //habilita o desabilita los botones del menu
         btnNuevo.setEnabled(false);
        
        btnCancelar.setEnabled(true);
//        btnGuardar.setEnabled(true);
        btnLimpiar.setEnabled(true);
        //habilita las cajas de texto del formulario 
        jcFecha.setEnabled(true);
        txtNombreCliente.setEnabled(true);
        txtRuc.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtCorreo.setEnabled(true);
       } public void cargarDatosProductoInventarioFormulario() {

       
            Integer fila = tDatosinventario.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "Se debe seleccionar un registro");
            } else {
                dtmI = (DefaultTableModel) tDatosinventario.getModel();
                lblIdinventario.setText((String)tDatosinventario.getValueAt(fila, 0));
                txtPrecio.setText((String)tDatosinventario.getValueAt(fila, 1));
                txtStock.setText((String)tDatosinventario.getValueAt(fila, 2));
                pro = new productos(Integer.parseInt(dtmI.getValueAt(fila, 0).toString()),
                        (String) dtmI.getValueAt(fila, 1),
                        (String) dtmI.getValueAt(fila, 2),
                        (String) dtmI.getValueAt(fila, 3),
                        (String) dtmI.getValueAt(fila, 4),
                        (String) dtmI.getValueAt(fila, 5));
            }
            

        
        System.out.println(pro.mostrarDatos()+inv.mostrarDatos());
//        lblIdProducto.setText(pro.getIdProducto().toString());
        txtNombreproducto.setText(pro.getPRODESCRIPCION());
//        lblIdInventario.setText(inv.getIdInventario().toString());
        txtCodigoproducto.setText(pro.getPROCODIGO());
//        strCodigo = (pro.getIdProducto().toString());

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnvender;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private com.toedter.calendar.JDateChooser jcFecha;
    private javax.swing.JLabel lblIdinventario;
    private javax.swing.JLabel lblTotalInventario;
    private javax.swing.JLabel lblTotalRegistros;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pBuscar2;
    private javax.swing.JPanel pBuscarcliente;
    private javax.swing.JPanel pformularioFactura;
    private javax.swing.JRadioButton rbtnApellido;
    private javax.swing.JRadioButton rbtnCedula;
    private javax.swing.JRadioButton rbtnIdCliente;
    private javax.swing.JRadioButton rbtnIdinventario;
    private javax.swing.JRadioButton rbtnNombre;
    private javax.swing.JRadioButton rbtnProducto;
    private javax.swing.JRadioButton rbtnProveedor;
    private javax.swing.JTable tDatos;
    private javax.swing.JTable tDatoscliente;
    private javax.swing.JTable tDatosfa;
    private javax.swing.JTable tDatosinventario;
    private javax.swing.JTabbedPane tbDatos;
    private javax.swing.JLabel totalRegistros;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtBusquedainventario;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoproducto;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdcliente;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreproducto;
    private javax.swing.JTextField txtNumfactura;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
