/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Component;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import modelo.productos;

/**
 *
 * @author darwi
 */
public class jifrmProductos extends javax.swing.JInternalFrame {
    productos n= new productos(title, title, title, title, title);
   
  String titulos[] = {"idPRODUCTO","DESCRIPCION","CODIGO","UNIDADMEDIDA","INFORMACIONNUTRICIONAL","OBSERVACION"};
  DefaultTableModel dtm = new DefaultTableModel(null, titulos);
  
  String criterio, busqueda, strCodigo;
    Integer busquedaInt;
    static ResultSet rs = null;
    productos c = new productos();
    public jifrmProductos() {
        initComponents();
        rbtnIdEmpleados.setSelected(true);
        buscarProducto();   
        habilitarBotonesInicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotalRegistros = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        tbDatos = new javax.swing.JTabbedPane();
        pFormularioDatos = new javax.swing.JPanel();
        lblidproductos = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtProcodigo = new javax.swing.JTextField();
        txtUnidadMedia = new javax.swing.JTextField();
        txtInformacionNutricional = new javax.swing.JTextField();
        txtObservacion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        pDatos = new javax.swing.JPanel();
        rbtnIdEmpleados = new javax.swing.JRadioButton();
        rbtnNombre = new javax.swing.JRadioButton();
        rbtnApellido = new javax.swing.JRadioButton();
        rbtnCedula = new javax.swing.JRadioButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDatos = new javax.swing.JTable();
        lblTotalRegistros1 = new javax.swing.JLabel();

        lblTotalRegistros.setBorder(javax.swing.BorderFactory.createTitledBorder("total registro"));

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jToolBar1.setRollover(true);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo2.png"))); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setMaximumSize(new java.awt.Dimension(60, 75));
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNuevo);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngegg (1).png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setMaximumSize(new java.awt.Dimension(70, 75));
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setMaximumSize(new java.awt.Dimension(70, 75));
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelar);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar 2.png"))); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setFocusable(false);
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setMaximumSize(new java.awt.Dimension(70, 80));
        btnLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimpiar);

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar3.png"))); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setFocusable(false);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.setMaximumSize(new java.awt.Dimension(80, 75));
        btnActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnActualizar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setMaximumSize(new java.awt.Dimension(70, 75));
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminar);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir_1.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setMaximumSize(new java.awt.Dimension(60, 75));
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSalir);

        lblidproductos.setBorder(javax.swing.BorderFactory.createTitledBorder("IDPRODUCTO"));

        txtDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("PRODESCRIPCION"));

        txtProcodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("PROCODIGO"));

        txtUnidadMedia.setBorder(javax.swing.BorderFactory.createTitledBorder("PROUNIDADMEDIDA"));

        txtInformacionNutricional.setBorder(javax.swing.BorderFactory.createTitledBorder("PROINFORMACIONNUTRICIONAL"));

        txtObservacion.setBorder(javax.swing.BorderFactory.createTitledBorder("PROOBSERVACION"));

        javax.swing.GroupLayout pFormularioDatosLayout = new javax.swing.GroupLayout(pFormularioDatos);
        pFormularioDatos.setLayout(pFormularioDatosLayout);
        pFormularioDatosLayout.setHorizontalGroup(
            pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormularioDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtObservacion, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(txtDescripcion)
                    .addComponent(txtProcodigo)
                    .addComponent(txtUnidadMedia)
                    .addComponent(txtInformacionNutricional)
                    .addComponent(lblidproductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(564, Short.MAX_VALUE))
        );
        pFormularioDatosLayout.setVerticalGroup(
            pFormularioDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormularioDatosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblidproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnidadMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInformacionNutricional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        tbDatos.addTab("Datos Clientes", pFormularioDatos);

        pDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("BUSCAR POR"));

        buttonGroup1.add(rbtnIdEmpleados);
        rbtnIdEmpleados.setText("idProductos");

        buttonGroup1.add(rbtnNombre);
        rbtnNombre.setText("caracteristicas");

        buttonGroup1.add(rbtnApellido);
        rbtnApellido.setText("Codigo");

        buttonGroup1.add(rbtnCedula);
        rbtnCedula.setText("unidad de medicion");

        txtBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese el texto de busqueda"));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pDatosLayout = new javax.swing.GroupLayout(pDatos);
        pDatos.setLayout(pDatosLayout);
        pDatosLayout.setHorizontalGroup(
            pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar)
                    .addGroup(pDatosLayout.createSequentialGroup()
                        .addComponent(rbtnIdEmpleados)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnNombre)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnApellido)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnCedula)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pDatosLayout.setVerticalGroup(
            pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnIdEmpleados)
                    .addComponent(rbtnNombre)
                    .addComponent(rbtnApellido)
                    .addComponent(rbtnCedula))
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        tDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tDatos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tDatos);

        lblTotalRegistros1.setBorder(javax.swing.BorderFactory.createTitledBorder("total registro"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalRegistros1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(lblTotalRegistros1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbDatos.addTab("Busacar", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tbDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 808, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 597, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(116, Short.MAX_VALUE)
                    .addComponent(tbDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void habilitarBotonesProceso(){
        //habilita o desabilita los botones del menu
        btnNuevo.setEnabled(false);
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnLimpiar.setEnabled(true);
        //habilita las cajas de texto del formulario 
        txtDescripcion.setEnabled(true);
        txtInformacionNutricional.setEnabled(true);
        txtObservacion.setEnabled(true);
        txtProcodigo.setEnabled(true);
        txtUnidadMedia.setEnabled(true);
       
    }
    private void  habilitarBotonesInicio(){
          //habilita o desabilita los botones del menu
        btnNuevo.setEnabled(false);
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnLimpiar.setEnabled(true);
        btnSalir.setEnabled(true);
        //habilita las cajas de texto del formulario 
        txtDescripcion.setEnabled(true);
        txtProcodigo.setEnabled(true);
        txtUnidadMedia.setEnabled(true);
        txtInformacionNutricional.setEnabled(true);
        txtObservacion.setEnabled(true);
    
    
    
    }
    public void buscarProducto() {
        busqueda = txtBuscar.getText();
        if (rbtnIdEmpleados.isSelected()) {
            criterio = "IDPRODUCTOS";
        } else if (rbtnNombre.isSelected()) {
            criterio = "DESCRIPCION";
        } else if (rbtnApellido.isSelected()) {
            criterio = "CODIGO";
        } else if (rbtnCedula.isSelected()) {
            criterio = "UNIDADMEDIDA";
        }
        System.out.println(criterio + " " + busqueda);
        try {
            dtm = c.SP_S_productosParametro(criterio, busqueda);
            Integer filas = dtm.getRowCount();
            lblTotalRegistros1.setText(filas.toString());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        tDatos.setModel(dtm);
        columnasAutoAjustable(tDatos);
    }
public void columnasAutoAjustable(JTable tabla) {
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int column = 0; column < tabla.getColumnCount(); column++) {
            TableColumn columnaTabla = tabla.getColumnModel().getColumn(column);
            int anchoMinimo = columnaTabla.getMinWidth();
            int anchoMaximo = columnaTabla.getMaxWidth();

            for (int fila = 0; fila < tabla.getRowCount(); fila++) {
                TableCellRenderer cambiarAnchoCelda = tabla.getCellRenderer(fila, column);
                Component c = tabla.prepareRenderer(cambiarAnchoCelda, fila, column);
                int ancho = c.getPreferredSize().width + tabla.getIntercellSpacing().width;
                anchoMinimo = Math.max(anchoMinimo, ancho);

                //  We've exceeded the maximum width, no need to check other rows
                if (anchoMinimo >= anchoMaximo) {
                    anchoMinimo = anchoMaximo;
                    break;
                }
            }

            columnaTabla.setPreferredWidth(anchoMinimo);
        }
    }
public void habilitarBotonesProcesoCargar(){
        //habilita o desabilita los botones del menu
        btnNuevo.setEnabled(false);
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnLimpiar.setEnabled(true);
        //habilita las cajas de texto del formulario 
        txtDescripcion.setEnabled(true);
        txtProcodigo.setEnabled(true);
        txtUnidadMedia.setEnabled(true);
        txtInformacionNutricional.setEnabled(true);
        txtObservacion.setEnabled(true);
   
}
public void limpiarBuscar() {
        txtBuscar.setText("");
        buscarProducto();
    }
public void cargarDatosFormulario(String msj) {

        if (msj.equals("limpiar")) {
            n = new productos();
        } else if(msj.equals("cargarDatos")){
            Integer fila = tDatos.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "Se debe seleccionar un registro");
            } else {
                dtm = (DefaultTableModel) tDatos.getModel();
                    n = new productos(Integer.parseInt(dtm.getValueAt(fila, 0).toString()),

                        (String) dtm.getValueAt(fila, 1),
                        (String) dtm.getValueAt(fila, 2),
                        (String) dtm.getValueAt(fila, 3),
                        (String) dtm.getValueAt(fila, 4),
                        (String) dtm.getValueAt(fila, 5));
            }

        }
        System.out.println(n.mostrarDatos());
        lblidproductos.setText(n.getIDPRODUCTO().toString());
  
  txtDescripcion.setText(n.getPRODESCRIPCION());
        txtProcodigo.setText(n.getPROCODIGO());
        txtUnidadMedia.setText(n.getPROUNIDADMEDIDA());
        txtInformacionNutricional.setText(n.getPROINFORMACIONNUTRICIONAL());
        txtObservacion.setText(n.getPROOBSERVACION());
       
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
 n = new productos(txtDescripcion.getText(),
                 txtProcodigo.getText(),
                 txtUnidadMedia.getText(),
                txtInformacionNutricional.getText(),
                txtObservacion.getText());
                
                
                
        n.guardar();
        habilitarBotonesInicio();        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
  cargarDatosFormulario("limpiar");
        habilitarBotonesProceso();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
                                       
        n= new productos(Integer.parseInt(lblidproductos.getText()), txtDescripcion.getText(), txtProcodigo.getText(), txtUnidadMedia.getText(), txtInformacionNutricional.getText(), txtObservacion.getText());
        n.actualizar();
        buscarProducto();
        cargarDatosFormulario("limpiar");
        habilitarBotonesInicio();
            // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
//        cli = new clientes(Integer.parseInt(lblIdCliente.getText()), txtApellidos.getText(), txtNombres.getText(), txtCedula.getText(), txtCorreo.getText(), txtTelefono.getText(), txtDireccion.getText());
        n.eliminar();
        cargarDatosFormulario("limpiar");
        habilitarBotonesInicio();
        buscarProducto();        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      habilitarBotonesProceso();
        tbDatos.setSelectedComponent(pFormularioDatos);  
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
       buscarProducto(); // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDatosMouseClicked
cargarDatosFormulario("cargarDatos");
        if(evt.getClickCount() == 2) {
            tbDatos.setSelectedComponent(pFormularioDatos);
        }
        habilitarBotonesProcesoCargar();        // TODO add your handling code here:
    }//GEN-LAST:event_tDatosMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
  cargarDatosFormulario("limpiar");
        habilitarBotonesInicio();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblTotalRegistros;
    private javax.swing.JLabel lblTotalRegistros1;
    private javax.swing.JLabel lblidproductos;
    private javax.swing.JPanel pDatos;
    private javax.swing.JPanel pFormularioDatos;
    private javax.swing.JRadioButton rbtnApellido;
    private javax.swing.JRadioButton rbtnCedula;
    private javax.swing.JRadioButton rbtnIdEmpleados;
    private javax.swing.JRadioButton rbtnNombre;
    private javax.swing.JTable tDatos;
    private javax.swing.JTabbedPane tbDatos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtInformacionNutricional;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextField txtProcodigo;
    private javax.swing.JTextField txtUnidadMedia;
    // End of variables declaration//GEN-END:variables
}
